
<?xml version="1.0" encoding="UTF-8"?>
<!--DTD -->
<!DOCTYPE dataset [
	<!ELEMENT dataset (station)*>
	<!ATTLIST dataset lat CDATA #REQUIRED long CDATA #REQUIRED msg CDATA #REQUIRED>
	<!ELEMENT station (county,municipality,dd,address,companyName,lat,long,h24,brand,phone+,fuels)*>
	<!ATTLIST station distance CDATA #REQUIRED stationID CDATA #REQUIRED>
	<!ELEMENT county (#PCDATA)>
	<!ATTLIST county countyID CDATA #REQUIRED>
	<!ELEMENT municipality (#PCDATA)>
	<!ATTLIST municipality municipalityID CDATA #REQUIRED>
	<!ELEMENT dd (#PCDATA)>
	<!ATTLIST dd ddID CDATA #REQUIRED>
	<!ELEMENT address (#PCDATA)>
	<!ELEMENT companyName (#PCDATA)>
	<!ELEMENT lat (#PCDATA)>
	<!ELEMENT long (#PCDATA)>
	<!ELEMENT h24 EMPTY>
	<!ATTLIST h24 value (0|1) #IMPLIED>
	<!ELEMENT brand (#PCDATA)>
	<!ATTLIST brand brandID CDATA #REQUIRED>
	<!ELEMENT phone (#PCDATA)>
	<!ELEMENT fuels (fuel)*>
	<!ELEMENT fuel (#PCDATA)>
	<!ATTLIST fuel fuelTypeID CDATA #REQUIRED price CDATA #REQUIRED priceTimeStamp CDATA #REQUIRED>
]>
<!--XML -->
<dataset msg="Hello User" long="40.12222" lat="23.122222">
	<station distance="1.8" stationID="00001">
		<county countyID="GR 300">Ελλάδα</county>
		<municipality municipalityID="41336">Λάρισα</municipality>
		<dd ddID="1111">Δήμος Λάρισας</dd>
		<address><![CDATA[
		            Βόλου 12, Λάρισα
				 ]]>
		</address>
		<companyName><![CDATA[
		            ΑΦΟΙ ΔΡΑΜΗ Κ. Ο.Ε.
				     ]]>
		</companyName>
		<lat>23.111456</lat>
		<long>41.1114567</long>
		<h24 value="0"/>
		<brand brandID="1">EKO</brand>
		<phone>2410283954</phone>
		<phone>2410550477</phone>
		<fuels>
		    <fuel priceTimeStamp="2024-04-21 22:35:00"
			  price="1.959"
			  fuelTypeID="1">EKO Kinitron Unleaded 95</fuel>
		    <fuel priceTimeStamp="2024-04-21 22:35:00"
				  price="1.769"
				  fuelTypeID="2">EKO DIESEL Avio</fuel>
			</fuels>
	</station>
	<station distance="2.4" stationID="00002">
		<county countyID="GR 300">Ελλάδα</county>
		<municipality municipalityID="41223">Λάρισα</municipality>
		<dd ddID="2222">Δήμος Λάρισας</dd>
		<address><![CDATA[
		            Φαρσάλων 99, Λάρισα 
				 ]]>
		</address>
		<companyName><![CDATA[
		            ΜΑΚΡΑΙΩΝ Α.Ε.
				     ]]>
		</companyName>
		<lat>23.223456</lat>
		<long>41.2234567</long>
		<h24 value="0"/>
		<brand brandID="2">AVIN</brand>
		<phone>2410555388</phone>
		<fuels>
			<fuel priceTimeStamp="2024-04-22 05:55:00"
					      price="1.939"
					      fuelTypeID="1">Αμόλυβδη AVIN best 95</fuel>
			<fuel priceTimeStamp="2024-04-22 05:55:00"
					      price="1.655"
					      fuelTypeID="2">AVIN Diesel Best</fuel>
		</fuels>
	</station>
	<station distance="3.4" stationID="00003">
		<county countyID="GR 300">Ελλάδα</county>
		<municipality municipalityID="40003">Αγιά Λάρισας</municipality>
		<dd ddID="3333">Δήμος Αγιάς</dd>
		<address><![CDATA[
		            Γερακάρι, Αγιάς
				 ]]>
		</address>
		<companyName><![CDATA[
	                ΒΑΣΙΛΕΙΟΣ ΧΡΙΣΤΟΥΛΑΣ Ο.Ε.
					]]>
		</companyName>
		<lat>23.333333</lat>
		<long>41.333333</long>
		<h24 value="1"/>
		<brand brandID="3">BP</brand>
		<phone>2494041433</phone>
		<fuels>
			<fuel priceTimeStamp="2024-04-16 07:35:00"
					      price="2.026"
					      fuelTypeID="1">BP Unleaded 95</fuel>
			<fuel priceTimeStamp="2024-04-16 07:36:00"
					      price="1.719"
					      fuelTypeID="2">BP Super Diesel</fuel>
		</fuels>
	</station>
</dataset>
